import { ModelConfig } from '../types';

export const LOCAL_ENDPOINT = 'http://localhost:20128/v1';

export const DEFAULT_MODELS: ModelConfig[] = [
  // --- GPT 6.0 & GPT 5.x Series (cx/) ---
  {
    id: 'cx-gpt-6-astra',
    name: 'GPT 6.0 Astra',
    provider: 'openai',
    modelIdentifier: 'cx/gpt-6-astra',
    avatar: '🌟',
    badgeColor: '#10b981',
    playStyle: 'Frontier supreme intelligence, deep positional calculation',
    simulatedElo: 2750,
    description: 'GPT 6.0 Astra via local proxy endpoint.',
  },
  {
    id: 'cx-gpt-56-sol',
    name: 'GPT 5.6 Sol',
    provider: 'openai',
    modelIdentifier: 'cx/gpt-5.6-sol',
    avatar: '☀️',
    badgeColor: '#f59e0b',
    playStyle: 'Bright tactical attacking, dynamic piece sacrifices',
    simulatedElo: 2680,
    description: 'GPT 5.6 Sol model via local proxy endpoint.',
  },
  {
    id: 'cx-gpt-56-terra',
    name: 'GPT 5.6 Terra',
    provider: 'openai',
    modelIdentifier: 'cx/gpt-5.6-terra',
    avatar: '🌍',
    badgeColor: '#14b8a6',
    playStyle: 'Solid unshakeable pawn structures & fortress endgames',
    simulatedElo: 2660,
    description: 'GPT 5.6 Terra positional anchor model.',
  },
  {
    id: 'cx-gpt-56-luna',
    name: 'GPT 5.6 Luna',
    provider: 'openai',
    modelIdentifier: 'cx/gpt-5.6-luna',
    avatar: '🌙',
    badgeColor: '#6366f1',
    playStyle: 'Mysterious, subtle maneuverings and unexpected flank strikes',
    simulatedElo: 2650,
    description: 'GPT 5.6 Luna via local proxy endpoint.',
  },
  {
    id: 'cx-gpt-55',
    name: 'GPT 5.5',
    provider: 'openai',
    modelIdentifier: 'cx/gpt-5.5',
    avatar: '⚡',
    badgeColor: '#3b82f6',
    playStyle: 'High-speed classic grandmaster style, rapid opening play',
    simulatedElo: 2600,
    description: 'GPT 5.5 baseline model.',
  },
  {
    id: 'cx-gpt-54',
    name: 'GPT 5.4',
    provider: 'openai',
    modelIdentifier: 'cx/gpt-5.4',
    avatar: '♟️',
    badgeColor: '#8b5cf6',
    playStyle: 'Harmonic piece development and center control',
    simulatedElo: 2550,
    description: 'GPT 5.4 model via local proxy endpoint.',
  },
  {
    id: 'cx-gpt-54-mini',
    name: 'GPT 5.4 Mini',
    provider: 'openai',
    modelIdentifier: 'cx/gpt-5.4-mini',
    avatar: '🚀',
    badgeColor: '#ec4899',
    playStyle: 'Lightweight, ultra-fast response moves under time pressure',
    simulatedElo: 2480,
    description: 'GPT 5.4 Mini fast tactical engine.',
  },
  {
    id: 'cx-gpt-53-codex-spark',
    name: 'GPT 5.3 Codex Spark',
    provider: 'openai',
    modelIdentifier: 'cx/gpt-5.3-codex-spark',
    avatar: '⚡',
    badgeColor: '#e11d48',
    playStyle: 'Hyper-calculated algorithmic chess logic',
    simulatedElo: 2520,
    description: 'Codex Spark high-precision algorithmic model.',
  },

  // --- Gemini & Claude Models (ag/) ---
  {
    id: 'ag-gemini-38-flash',
    name: 'Gemini 3.8 Flash',
    provider: 'openai',
    modelIdentifier: 'ag/gemini-3.8-flash',
    avatar: '⚡',
    badgeColor: '#38bdf8',
    playStyle: 'Ultra-fast frontier tactician with live reasoning',
    simulatedElo: 2580,
    description: 'Google Gemini 3.8 Flash via local proxy endpoint.',
  },
  {
    id: 'ag-gemini-38-flash-medium',
    name: 'Gemini 3.8 Flash (Medium)',
    provider: 'openai',
    modelIdentifier: 'ag/gemini-3.8-flash-medium',
    avatar: '💎',
    badgeColor: '#0ea5e9',
    playStyle: 'Deep thinking, high strategic accuracy & tool calling',
    simulatedElo: 2600,
    description: 'Gemini 3.8 Flash Medium reasoning tier.',
  },
  {
    id: 'ag-claude-opus-46',
    name: 'Claude Opus 4.6 (Thinking)',
    provider: 'openai',
    modelIdentifier: 'ag/claude-opus-4-6-thinking',
    avatar: '🧠',
    badgeColor: '#8b5cf6',
    playStyle: 'Deep foresight, profound positional and endgame mastery',
    simulatedElo: 2620,
    description: 'Anthropic Claude Opus 4.6 with reasoning via local endpoint.',
  },
  {
    id: 'ag-claude-sonnet-46',
    name: 'Claude Sonnet 4.6',
    provider: 'openai',
    modelIdentifier: 'ag/claude-sonnet-4-6',
    avatar: '🟧',
    badgeColor: '#f97316',
    playStyle: 'Sharp tactical balance, fluid attacks & rapid calculation',
    simulatedElo: 2560,
    description: 'Anthropic Claude Sonnet 4.6 via local endpoint.',
  },
  {
    id: 'ag-gpt-oss-120b',
    name: 'GPT-OSS 120B (Medium)',
    provider: 'openai',
    modelIdentifier: 'ag/gpt-oss-120b-medium',
    avatar: '🤖',
    badgeColor: '#10b981',
    playStyle: 'Massive open weights model with extensive step-by-step thinking',
    simulatedElo: 2540,
    description: 'GPT-OSS 120B Medium tier with extended reasoning traces.',
  },
  {
    id: 'ag-gemini-37-flash-medium',
    name: 'Gemini 3.7 Flash (Medium)',
    provider: 'openai',
    modelIdentifier: 'ag/gemini-3.7-flash-medium',
    avatar: '🔷',
    badgeColor: '#06b6d4',
    playStyle: 'Dynamic piece coordination and tactical defense',
    simulatedElo: 2510,
    description: 'Gemini 3.7 Flash Medium via local endpoint.',
  },
  {
    id: 'ag-gemini-36-flash-medium',
    name: 'Gemini 3.6 Flash (Medium)',
    provider: 'openai',
    modelIdentifier: 'ag/gemini-3.6-flash-medium',
    avatar: '💠',
    badgeColor: '#6366f1',
    playStyle: 'Direct tactical calculation and aggressive initiative',
    simulatedElo: 2460,
    description: 'Gemini 3.6 Flash Medium via local endpoint.',
  },
  {
    id: 'ag-gemini-3-flash',
    name: 'Gemini 3 Flash',
    provider: 'openai',
    modelIdentifier: 'ag/gemini-3-flash',
    avatar: '✨',
    badgeColor: '#a855f7',
    playStyle: 'Rapid instinctive move selection',
    simulatedElo: 2420,
    description: 'Gemini 3 Flash baseline model.',
  },
];
